version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: unica
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql
  
  kubenews:
    image: claudemirferreiraduxcod3/cicd:v1
    depends_on:
      - postgre
    build:
      context: ./src
      dockerfile: Dockerfile
    ports: 
      - 8080:8080

networks:
  my-network:

volumes:
  mysql-data:
