name: CI-CD

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Build and test
        run: mvn clean install

      - name: Obtendo o código
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.USER}}
          password: ${{secrets.PASSWORD}}
      - name: Construção da imagem Docker worker
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            claudemirferreiraduxcod3/myapp:${{github.run_number}}
            claudemirferreiraduxcod3/myapp:latest                

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.16.1
        with:
          image-ref: claudemirferreiraduxcod3/myapp:${{github.run_number}}
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: 0
          severity: UNKNOWN,CRITICAL,HIGH,MEDIUM,LOW

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Enviando a imagem
        run: |
          docker push claudemirferreiraduxcod3/myapp:${{github.run_number}}
          docker push claudemirferreiraduxcod3/myapp:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]

